# Generated by Django 3.0 on 2020-04-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Facción')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Facción',
                'verbose_name_plural': 'Facciones',
            },
        ),
    ]
