# Generated by Django 3.0 on 2020-04-19 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0004_typeattack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='atack',
            field=models.ForeignKey(help_text='Si el héroe ataca de rango o no', on_delete=django.db.models.deletion.CASCADE, to='things.TypeAttack', verbose_name='Ataca'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='team',
            field=models.ForeignKey(default='', help_text='Equipo o Facción al que pertenece el héroe.', on_delete=django.db.models.deletion.CASCADE, to='things.TypeTeam', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='type',
            field=models.ForeignKey(default='', help_text='Tipo del héroe', on_delete=django.db.models.deletion.CASCADE, to='things.TypeHero', verbose_name='Tipo'),
        ),
    ]
