# Generated by Django 3.0 on 2020-04-19 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0005_auto_20200419_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='team_win',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='things.TypeTeam'),
        ),
        migrations.AlterField(
            model_name='playersgame',
            name='game',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='things.Game'),
        ),
        migrations.AlterField(
            model_name='playersgame',
            name='team',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='things.TypeTeam'),
        ),
    ]
