# Generated by Django 3.0 on 2020-04-20 03:36

from django.db import migrations, models
import things.models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0006_auto_20200419_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='background',
            field=models.ImageField(default='', help_text='Background mostrado en la pagina de detalles del héroe.', null=True, upload_to=things.models.scramble_upload_background, verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='detail_pic',
            field=models.ImageField(default='', help_text='Imagen con una descripción del héroe, sus habilidades y recomendaciones.', null=True, upload_to=things.models.scramble_upload_detail, verbose_name='Detalle'),
        ),
        migrations.RemoveField(
            model_name='hero',
            name='skills',
        ),
        migrations.AddField(
            model_name='hero',
            name='skills',
            field=models.ManyToManyField(blank=True, default='', to='things.Skill', verbose_name='habilidades'),
        ),
    ]
