# Generated by Django 3.0 on 2020-04-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0007_auto_20200420_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersgame',
            name='damage',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='playersgame',
            name='experiens',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='playersgame',
            name='firstblood',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playersgame',
            name='firstblood_die',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playersgame',
            name='golds',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=10, null=True),
        ),
    ]
