# Generated by Django 3.0 on 2020-04-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0008_auto_20200424_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersgame',
            name='damage',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='playersgame',
            name='experiens',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='playersgame',
            name='golds',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=21, null=True),
        ),
    ]
