# Generated by Django 4.2.4 on 2023-09-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HonStatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamspeak_srv_url', models.CharField(blank=True, default='', help_text='Dirección Url del servidor TeamSpeak usado para jugar', max_length=500, verbose_name='Url Servidor TeamSpeak')),
                ('color_first_place', models.CharField(blank=True, default='green', help_text='Color the fuente del jugador que se encuentra en primer lugar en las estadisticas', max_length=10, verbose_name='Color Primer Lugar')),
                ('color_positive_ranking', models.CharField(blank=True, default='blue', help_text='Color the fuente del jugador cuyo promedio de puntuación es positivo', max_length=10, verbose_name='Color Ranking positivo')),
                ('color_negative_ranking', models.CharField(blank=True, default='red', help_text='Color the fuente del jugador cuyo promedio de puntuación es negativo', max_length=10, verbose_name='Color Ranking negativo')),
                ('color_last_place', models.CharField(blank=True, default='brown', help_text='Color the fuente del jugador que ocupa el último lugar en las estadíticas', max_length=10, verbose_name='Color Último Lugar')),
                ('min_games', models.PositiveSmallIntegerField(blank=True, default=20, help_text='Es el minimo de juegos que debe tener un jugador para calcular su promedio de puntos por los juegos jugados, en cambio si el jugado no tiene al menos ese numero de juegos jugados su promedio se calculará con ese número', verbose_name='Mínimo de Juegos')),
                ('kill_value', models.FloatField(blank=True, default=0.5, help_text='Valor o Peso que tiene cometer un asesianto en una partida, la modicación de este valor puede hacer que la acción de asesinar tome mayor o menor relevancia en las estadísticas', verbose_name='Peso del Asesinato')),
                ('dead_value', models.FloatField(blank=True, default=-0.3, help_text='Valor o Peso que tiene ser asesinado en una partida, la modicación de este valor puede hacer que la acción de morir tome mayor o menor relevancia en las estadísticas', verbose_name='Peso de Muerte')),
                ('assist_value', models.FloatField(blank=True, default=-0.25, help_text='Valor o Peso que tiene realizar una asistencia en una partida, la modicación de este valor puede hacer que dicha acción tome mayor o menor relevancia en las estadísticas', verbose_name='Peso de la Asistencia')),
                ('fkill_value', models.FloatField(blank=True, default=0.6, help_text='Valor o Peso que tiene cometer el primer asesinato en una partida, la modicación de este valor puede hacer que esta acción tome mayor o menor relevancia en las estadísticas', verbose_name='Peso de Primer Asesinato')),
                ('fdead_value', models.FloatField(blank=True, default=-0.5, help_text='Valor o Peso que tiene ser el primer asesinado en una partida, la modicación de este valor puede hacer que esta acción tome mayor o menor relevancia en las estadísticas', verbose_name='Peso de Primera Muerte')),
                ('win_value', models.FloatField(blank=True, default=0.8, help_text='Valor o Peso que tiene ganar una partida, la modicación de este valor puede hacer que esta acción tome mayor o menor relevancia en las estadísticas', verbose_name='Peso de la Vitoria')),
                ('loose_value', models.FloatField(blank=True, default=-0.4, help_text='Valor o Peso que tiene ser derrotado en una partida, la modicación de este valor puede hacer que esta acción tome mayor o menor relevancia en las estadísticas', verbose_name='Peso de la Derrota')),
            ],
            options={
                'verbose_name': 'HoN stats App settings',
            },
        ),
    ]
