# Generated by Django 4.2.4 on 2023-09-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honstatsettings',
            name='teamspeak_srv_url',
            field=models.CharField(blank=True, default='', help_text='Dirección Url del servidor TeamSpeak usado para jugar', max_length=500, verbose_name='Url Servidor TeamSpeak'),
        ),
    ]
