# Generated by Django 4.2.4 on 2023-09-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honauth', '0002_alter_honstatsettings_teamspeak_srv_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honstatsettings',
            name='color_last_place',
            field=models.CharField(blank=True, default='brown', help_text='Color the fuente del jugador que ocupa el último lugar en las estadíticas', max_length=10, verbose_name='Color Último Lugar'),
        ),
    ]
